name: auto_sync_fork

on:
  workflow_dispatch:
  # schedule:
  #   - cron: 15 21 */1 * *

jobs:
  build:
    runs-on: ubuntu-22.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Fork Sync
      uses: tgymnich/fork-sync@v2.0.9
    
